package com.journal.florist.app.common.utils.jasper;

import lombok.Data;
import net.sf.jasperreports.engine.JRDataSource;

import java.io.Serializable;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

@Data
public class JasperReportRequest implements Serializable {

    //Required information
    private String reportFileName;

    //Report parameter
    private Map<String, Object> parameters = new HashMap<>();

    //Data source
    private Collection<?> reportData;
    private JRDataSource dataSource;

    //Generated byte array
    private byte[] content;

    //Output file name
    private String outputFileName;

}
