spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tkbunga
    username: postgres
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          driver_class: org.postgresql.Driver
        format_sql: false
    hibernate:
      ddl-auto: none
    show-sql: false


